### ISSUE TITLE
Add multicontract capabilities

### ISSUE THREAD

**Issue by ad-ha** [ad-ha/ide_api#19]
Related with #18 

Add possibility to have readings for multiple contracts. Should support multi-entries to configuration and multi-sensors.

**Comment by liebefuroscar** [comment]
Estaría genial. Por aportar, diría que si crea un sensor para cada contrato, en vez de tener que elegir uno estaría fantástico.
Un saludo

**Comment by ad-ha** [comment]
Buenas,

Recomiendo que mires este topico: https://community.home-assistant.io/t/iberdrola-distribucion-i-de-energy-monitor-custom-integration-released/326602/127?u=varetas

Esta integración no se seguirá desarrollando, pero la nueva ya tiene esa funcionalidad.

Saludos
