### ISSUE TITLE
Add Sensor Attributes

### ISSUE THREAD

**Issue by ad-ha** [ad-ha/ide_api#20]
Currently the sensor only shows the meter readings. Would be good to include further sensors or attributes:

- No. Contrato
- CUPS
- Telegestionado
- Fecha última actualización
- Potencia máxima (contratada)

**Comment by ghiki** [comment]
Ya puestos, a esto se le podría añadir la creación de un segundo sensor en la misma lectura que devuelva el consumo instantáneo en el momento de la lectura (es un dato que ya se obtiene con la lectura). Y como me ha parecido leer en algún sitio, estaría bien meter por variable el tema del escaneo cada X tiempo (yo lo he tenido cada 15 minutos y no hay problema siempre que no lances chorricientas consultas de forma manual)
