### ISSUE TITLE
Platform error sensor.ide - No module named 'dateutil'

### ISSUE THREAD

**Issue by carlos-48** [ad-ha/ide_api#26]
Hi!

I'm looking to update Home Assistant to new version 2022.2, but when passing the Check Configuration tool, I get this error in the log:

`Platform error sensor.ide - No module named 'dateutil'`

Do you know how can I solve it? It's safe to update anyway?

**Comment by ad-ha** [comment]
Hi,

I updated to 2022.02 without any issues, although I am using the latest beta version of the integration: https://github.com/ad-ha/ide_api/releases/tag/v0.2.0-alpha

More info on the update here: https://community.home-assistant.io/t/iberdrola-distribucion-i-de-energy-monitor-beta-custom-component-released/326602/95?u=varetas

Would recommend that you try to update IDE before doing the 2022.02 update.
