### ISSUE TITLE
Tiempo de Escaneo 

### ISSUE THREAD

**Issue by jesusgarrigues** [ad-ha/ide_api#31]
Buenos días,

¿Se podría añadir el tiempo de escaneo como variable externa? Es decir , sino pongo la variable en yaml por defecto por ejemplo 60 minutos, pero también tener la opción de informarla mediante yaml

**Comment by ad-ha** [comment]
> ¿Se podría añadir el tiempo de escaneo como variable externa?

Buenas. Poder, sí se podía, pero no creo que sea conveniente (me imagino que sería para reducir el intervalo de consultas) ya que eso puede llevar a un baneo del acceso.

Lo recomendable es 1 hora.

**Comment by ad-ha** [comment]
Cerrado por falta de feedback
