### ISSUE TITLE
version 0.2 beta1 sensor no disponible

### ISSUE THREAD

**Issue by pepelillo** [ad-ha/ide_api#35]
Tengo instalada la version beta1 de la nueva version de codigo pero sigue apareciendo como sensor no disponible. aparentemente mi cuenta no esta baneada ya que desde la pagina de I-De accedo sin problemas con  mis credenciales.
Alguna idea?

**Comment by ad-ha** [comment]
Hola,

A mi me ha pasado lo mismo esta semana, después de actualizar HA al 2022.04. Al haber actualizado de nuevo al 2022.04.3 me ha vuelto a funcionar como esperado.

No he tenido oportunidad de ver qué pasa, pero me parece que había problemas con I-de, ya que al probar directamente en la web tampoco conseguia lecturas.

De momento, hasta que lo pueda mirar, solo puedo recomendar que vayas reiniciando (además de actualizar a HA 2022.04.3) y a ver si funciona. Lo siento por las molestias.

**Comment by pepelillo** [comment]
Actualizado a 2022.04.3 y reiniciado varias veces, pero sigue igual......... la web si me da lecturas, pero eso si no de manera consistente...... Pero lo raro es que me aparece como sensor no disponible cuando con el cambio no deberia pasar no?

**Comment by ad-ha** [comment]
> me aparece como sensor no disponible cuando con el cambio no deberia pasar no?

No, no debería pasar. Pero, al menos, hasta la semana que viene no lo podré mirar y ver qué puede estar causando que no funcione como era previsto.

**Comment by ad-ha** [comment]
Buenas

Estoy mirando esto pero no logro dar con el fallo. He reiniciado algunas veces mi HA para ver qué sale en el log, y cuando no puede obtener lectura me sale esto:

![image](https://user-images.githubusercontent.com/59612788/163817403-ad10e6b4-df4f-40e2-83c8-8336f6cbb3ac.png)

@pepelillo podrías mirar que errores salen en tú log? Gracias

**Comment by pepelillo** [comment]
2022-04-18 17:35:30 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform ide is taking over 10 seconds.

**Comment by pepelillo** [comment]
Logger: homeassistant.bootstrap
Source: bootstrap.py:428
First occurred: 17:44:39 (2 occurrences)
Last logged: 17:45:39

Waiting on integrations to complete setup: sensor.ide

**Comment by ad-ha** [comment]
Puedes ver el log completo y donde aparece ide ver que pone? Ahí es donde saldrá si hay error de conexión o qué puede pasar.

**Comment by pepelillo** [comment]
2022-04-18 17:45:53 ERROR (MainThread) [homeassistant.components.sensor] ide: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 735, in async_device_update
    await task
  File "/config/custom_components/ide/sensor.py", line 175, in async_update
    raise exception
  File "/config/custom_components/ide/sensor.py", line 172, in async_update
    self._state = await connection.current_kilowatt_hour_read()
  File "/usr/local/lib/python3.9/site-packages/oligo/asyncio/asynciber.py", line 95, in current_kilowatt_hour_read
    return (await self.measurement())["meter"]
  File "/usr/local/lib/python3.9/site-packages/oligo/asyncio/asynciber.py", line 84, in measurement
    data = await self.__request(WATTHOURMETER_URL)
  File "/usr/local/lib/python3.9/site-packages/oligo/asyncio/asynciber.py", line 58, in __request
    raise NoResponseException
oligo.exception.NoResponseException

**Comment by ad-ha** [comment]
Gracias. Por lo que veo es un problema en la conexión con i-DE desde Oligo.. y eso genera el error y hace que no cargue nada del módulo. Cuando hay una excepción con Oligo eso se dejo fuera de la espera y por eso el módulo falla.

Intentaré ver si lo puedo cambiar (no prometo que lo pueda hacer pronto).

Mientras, en la página de i-DE, prueba a ver qué te sale en el histórico de conexiones (https://www.i-de.es/consumidores/web/home/personal-area/connections-history) y a ver si las que ponen `Linux -` en Sistema Operativo dan conectado o algún otro mensaje.

Gracias

**Comment by pepelillo** [comment]
He comprobado las conexiones, yo uso manjaro por lo que hay varias etiquetadas como linux, pero he visto algunas etiquetadas como linux y como agente navegador Chrome, y oyo uso firefox, por lo que quiza sean las conexiones de oligo, me aparecen como conexiones hechas sin mensaje adicional.
Muchas gracias por el soporte, la verdad es que es un addon muy interesante, a mi me es muy util.

**Comment by pepelillo** [comment]
Hola. He testeado la libreria Oligo desde linea de comando de HassOS y funciona perfectamente. Tarda unos segundos pero funciona.

**Comment by ad-ha** [comment]
Pues, sigo sin saber qué decirte. Estos días he tenido que reiniciar HA varias veces y el sensor siempre se cargar, incluso antes, de obtener respuesta de i-DE. Así que, de momento, no soy capaz de dar con el problema.

**Comment by pepelillo** [comment]
LAstima, entonces ¿ solo queda como ultima opcion hacer que que Oligo se quede fuera de la espera como dices?, no se en que puedo ayudar para disponer del addon, me es muy util...

**Comment by pepelillo** [comment]
Con la ultima actualizacion del Core, el sensor ha vuelto a funcionar....... Espero que continue asi..... Gracias de todas formas por el soporte.

**Comment by ad-ha** [comment]
> Con la ultima actualizacion del Core, el sensor ha vuelto a funcionar....... Espero que continue asi..... Gracias de todas formas por el soporte.

Me alegro que haya vuelto a funcionar. Yo sinceramente no he dado con el fallo. Un saludo
