### ISSUE TITLE
Obtener consumo en W en vez de kW

### ISSUE THREAD

**Issue by ghiki** [ad-ha/ide_api#36]
Hay alguna posibidad de añadir la opción de obtener en W en vez de en KW el consumo del contador?

Actualmente no admite decimales la lectura, pero si en lugar de obtener los kW obtenemos los W, y luego mediante un Template lo convertimos en kW o lo que queramos, si que podríamos tener los consumos más realistas con kW con decimales

Actualmente a mi está consulta de Oligo me devuelve en W en vez de kW (hay que quitar la fecha, ya que lo tengo para que me dé el consumo desde el día 1), creo que lo postee también en uno de los comentarios del Git de Oligo

```import os
package = "oligo"
try:
	     __import__(package)
except:
		os.system("pip install "+ package)
#
from oligo import Iber
from datetime import date, timedelta
#
connection = Iber()
connection.login("xxxxx@xxx.com", "xxxxxxxx")
#
from_date = date.today().replace(day=1)
#until_date = date.today() - timedelta(days=2)
until_date = date.today()
#
consumo = connection.consumption(from_date, until_date)
#
#print(consumo)
quitanone = [i for i in consumo if i] 
#Damos en Watios
suma=sum(quitanone)
#Convertimos en Kw
enkw=(suma)/1000
#print("Hasta", (until_date))
print(suma)

```

**Comment by ad-ha** [comment]
Hola,

La lectura del contador solo da números enteros, sin decimales, por lo que aunque pasará a W sería lo mismo.

Una opción seria luego recoger los datos horários de i-DE (ya con decimales) y reemplazar las lecturas (una vez eso se muestre consolidado en i-DE, ya que tarda unos días). Pero esto no lo sé hacer, ni si es posible en HA.

Tú consulta lo que hace es verificar esos datos consolidados, pero no el consumo instantáneo; ya que como decía, los datos horarios tardan unos días en estar disponibles.

**Comment by ghiki** [comment]
Vale, ya he visto a lo que te refieres, que la lectura del contador te la da en KW desde la API REST de I-de (está misma lectura en W seria lo ideal para tener datos precisos). Sobre lo segundo que dices...ni idea, habría que sustituir valores ya guardados en el HA, tampoco tendría mucho sentido porque hasta pasado un día al menos, no tendrías la lectura real (así que los contadores "daily" y "hourly" no ofrecerían nada "real")

**Comment by ad-ha** [comment]
A eso me referia, sí.

Lo de actualizar los históricos (que tampoco creo que se pueda) era por tener datos más exactos y cuadrados con i-DE.

Aún así, mientras no haya una API directa de I-DE con esta funcionalidad, no creo que podamos sacar decimales en tiempo real.

Un saludo

**Comment by ad-ha** [comment]
Cerrado
