### ISSUE TITLE
Posibilidad de crear un sensor para los kwh exportados

### ISSUE THREAD

**Issue by folch1963** [ad-ha/ide_api#37]
Acabo de ver la integración y la he instalado. Me parece una maravilla.
No sé si es posible pero sería interesante que también pudieramos obtener los datos de la energía exportada, para el caso de quienes tienen instalaciones fotovoltaicas conectadas a la red.
Gracias por vuestro trabajo.

**Comment by ad-ha** [comment]
Cerrado por cierre de proyecto
