### ISSUE TITLE
README

### ISSUE THREAD

**Issue by alessbarb** [ad-ha/ide_api#4]
Fantástico trabajo el vuestro. Sólo pediros una cosa, cuando tengáis un momento actualizad README para incluir lo que bien indicáis en este post: https://community.home-assistant.io/t/iberdrola-distribucion-i-de-energy-monitor-beta-custom-component-released/326602/38

Facilitará la implementación. Yo me lo acabo de bajar de HACS integrando tu repositorio como nuevo repositorio de Integración y ahora voy a configurar configuration.yaml añadiendo lo que indicas en el post.

Si surge cualquier cosa te aviso con una nueva issue.

Si necesitas cualquier ayuda estoy disponible, mis conocimientos de programación son limitados, pero lo que pueda te ayudo.

De nuevo, fantástico trabajo. ¡Muchas gracias!

**Comment by alessbarb** [comment]
También lo que viene en este post: https://community.home-assistant.io/t/iberdrola-distribucion-i-de-energy-monitor-beta-custom-component-released/326602/20

**Comment by ad-ha** [comment]
Buenas @alessbarb 

Gracias por el comentario. Realmente es una de las cosas que tengo pendientes, pero con las festividades todavía no encontré el tiempo para hacerlo.

La semana que viene, seguramente, lo pueda preparar.

**Comment by NeoMorfeo** [comment]
> Buenas @alessbarb
> 
> Gracias por el comentario. Realmente es una de las cosas que tengo pendientes, pero con las festividades todavía no encontré el tiempo para hacerlo.
> 
> La semana que viene, seguramente, lo pueda preparar.

Si quieres, lo hago yo en un fork, y te pido un merge, para actualizarlo, que eso es sencillo :)

**Comment by alessbarb** [comment]
Acabo de hacerlo yo ahora que tenía un ratito.

**Comment by NeoMorfeo** [comment]
ohh! estaba terminandolo :D ejjeje lo subiré a mi repo y si eso complementamos

**Comment by ad-ha** [comment]
Buenas @alessbarb y @NeoMorfeo

**Gracias a lo dos**. 

He subido el pull que tenía. Tengo en mente hacer algunos otros cambios, pero con las fiestas y niños en casa, la verdad que apenas tengo tiempo.

La semana que viene, ya me pongo con ello y lo vamos rematando mejor.

Un saludo

**Comment by ad-ha** [comment]
Closed: Issue #4 resolved with README.md update commit from #5

**Comment by NeoMorfeo** [comment]
> Buenas @alessbarb y @NeoMorfeo
> 
> **Gracias a lo dos**.
> 
> He subido el pull que tenía. Tengo en mente hacer algunos otros cambios, pero con las fiestas y niños en casa, la verdad que apenas tengo tiempo.
> 
> La semana que viene, ya me pongo con ello y lo vamos rematando mejor.
> 
> Un saludo

Sin problema, sabemos como es todo, cuando se pueda, me gusta colaborar y ayudar, solo pídelo y si puedo, ayudaré! :)

**Comment by alessbarb** [comment]
Ídem, le acabo de dar al botón de pull que no le había confirmado, no me había fijado en este comentario. Puedes rechazar lo mío si lo consideras.

Gracias.
